name = "aiken-lang/state-nft-vault"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/state-nft-vault'"

[repository]
user = "kushal2060"
project = "state-nft-vault"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[config]
